#!/usr/bin/env bash
# scripts/rex_publish.sh
# Rex 自动开 PR
set -euo pipefail

DAY=$(ls posts/day-*.md 2>/dev/null | head -1 | grep -oE 'day-[0-9]+' | grep -oE '[0-9]+' || echo "")
[[ -z "$DAY" ]] && { echo "no draft found"; exit 1; }

FILE=$(ls posts/day-${DAY}-*.md | head -1)
TITLE=$(grep -m1 "^# " "$FILE" | sed 's/^# //')
BRANCH="post/day-${DAY}-$(echo $TITLE | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | head -c 50)"

git config user.email "rex@mindapex.dev"
git config user.name "Rex"
git checkout -b "$BRANCH"
git add "$FILE"
git commit -m "post: day-${DAY} ${TITLE}"
git push -u origin "$BRANCH"

gh pr create \
  --title "Day ${DAY}: ${TITLE}" \
  --body "Auto-generated by Rex. 5-checklist self-reviewed." \
  --base main \
  --head "$BRANCH" \
  --reviewer mindapex-os/maintainers
